# Generated by Django 5.2.9 on 2025-12-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
