# Generated by Django 5.2.5 on 2026-01-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location_access',
            field=models.CharField(choices=[('anywhere', 'Anywhere'), ('nearby', 'Nearby Only (500m)')], default='anywhere', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='public', max_length=10),
        ),
    ]
