# Generated by Django 5.2.5 on 2026-01-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_postmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
